### ISSUE TITLE
Handle load and run timeouts better

### ISSUE THREAD

**Issue by huntc** [typesafehub/conductr-cli#101]
When either loading or running a bundle, if the request times out then I think we should explain the common reasons why e.g. roles may not be matched. Presently, for load, the user will get:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 376, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 378, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1174, in getresponse
    response.begin()
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 282, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 243, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/requests/adapters.py", line 376, in send
    timeout=timeout
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 609, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/util/retry.py", line 247, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/packages/six.py", line 310, in reraise
    raise value
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 559, in urlopen
    body=body, headers=headers)
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 380, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 308, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='192.168.99.100', port=9005): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/conduct", line 9, in <module>
    load_entry_point('conductr-cli==0.23', 'console_scripts', 'conduct')()
  File "/usr/local/lib/python3.5/site-packages/conductr_cli/conduct.py", line 297, in run
    is_completed_without_error = args.func(args)
  File "/usr/local/lib/python3.5/site-packages/conductr_cli/validation.py", line 40, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/conductr_cli/validation.py", line 56, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/conductr_cli/validation.py", line 74, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/conductr_cli/validation.py", line 91, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/conductr_cli/validation.py", line 111, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/conductr_cli/validation.py", line 127, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/conductr_cli/validation.py", line 143, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/conductr_cli/validation.py", line 159, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/conductr_cli/conduct_load.py", line 26, in load
    return load_v1(args)
  File "/usr/local/lib/python3.5/site-packages/conductr_cli/conduct_load.py", line 56, in load_v1
    response = requests.post(url, files=files, timeout=LOAD_HTTP_TIMEOUT)
  File "/usr/local/lib/python3.5/site-packages/requests/api.py", line 107, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/requests/adapters.py", line 449, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='192.168.99.100', port=9005): Read timed out. (read timeout=30)
```

**Comment by typesafe-tools** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;zCe6M8pJ&#x2F;166-handle-load-and-run-timeouts-better"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Handle load and run timeouts better</a>

**Comment by fsat** [comment]
PR #103 addressed this.
