### ISSUE TITLE
Conduct Version command breaks

### ISSUE THREAD

**Issue by fsat** [typesafehub/conductr-cli#179]
CLI version `0.41`

```
ubuntu@ip-10-0-1-200:~$ conduct version
Encountered unexpected error.
Reason: AttributeError 'Namespace' object has no attribute 'dcos_mode'
Further information of the error can be found in the error log file: /home/ubuntu/.conductr/errors.log
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/conductr_cli/main_handler.py", line 8, in run
    result = callback()
  File "/usr/local/lib/python3.5/dist-packages/conductr_cli/conduct.py", line 6, in main_method
    conduct_main.run()
  File "/usr/local/lib/python3.5/dist-packages/conductr_cli/conduct_main.py", line 368, in run
    args.cli_parameters = get_cli_parameters(args)
  File "/usr/local/lib/python3.5/dist-packages/conductr_cli/conduct_main.py", line 286, in get_cli_parameters
    if not args.dcos_mode:
AttributeError: 'Namespace' object has no attribute 'dcos_mode'
```

**Comment by fsat** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ConductR CLI: conduct version breaks](https://trello.com/c/AXKwNWwh/379-conductr-cli-conduct-version-breaks)

**Comment by fsat** [comment]
Manual test for https://github.com/typesafehub/conductr-cli/issues/179 is done successfully.

**Setup**

Run a local instal using pip3 install -e .

```
Felixs-MacBook-Pro-2:conductr-cli felixsatyaputra$ pip3 install -e .
Obtaining file:///Users/felixsatyaputra/workspace/typesafe-fsat/conductr-cli
Requirement already satisfied (use --upgrade to upgrade): requests>=2.11.1 in /usr/local/lib/python3.5/site-packages (from conductr-cli==0.41)
Requirement already satisfied (use --upgrade to upgrade): argcomplete>=0.8.1 in /usr/local/lib/python3.5/site-packages (from conductr-cli==0.41)
Requirement already satisfied (use --upgrade to upgrade): pyhocon==0.2.1 in /usr/local/lib/python3.5/site-packages (from conductr-cli==0.41)
Requirement already satisfied (use --upgrade to upgrade): arrow>=0.6.0 in /usr/local/lib/python3.5/site-packages (from conductr-cli==0.41)
Requirement already satisfied (use --upgrade to upgrade): jsonschema==2.4 in /usr/local/lib/python3.5/site-packages (from conductr-cli==0.41)
Requirement already satisfied (use --upgrade to upgrade): pager<4.0,>=3.3 in /usr/local/lib/python3.5/site-packages (from conductr-cli==0.41)
Requirement already satisfied (use --upgrade to upgrade): prettytable<1.0,>=0.7 in /usr/local/lib/python3.5/site-packages (from conductr-cli==0.41)
Requirement already satisfied (use --upgrade to upgrade): pygments<3.0,>=2.0 in /usr/local/lib/python3.5/site-packages (from conductr-cli==0.41)
Requirement already satisfied (use --upgrade to upgrade): six<2.0,>=1.9 in /usr/local/lib/python3.5/site-packages (from conductr-cli==0.41)
Requirement already satisfied (use --upgrade to upgrade): toml<1.0,>=0.9 in /usr/local/lib/python3.5/site-packages (from conductr-cli==0.41)
Requirement already satisfied (use --upgrade to upgrade): pyparsing==2.0.3 in /usr/local/lib/python3.5/site-packages (from pyhocon==0.2.1->conductr-cli==0.41)
Requirement already satisfied (use --upgrade to upgrade): python-dateutil in /usr/local/lib/python3.5/site-packages (from arrow>=0.6.0->conductr-cli==0.41)
Installing collected packages: conductr-cli
  Running setup.py develop for conductr-cli
Successfully installed conductr-cli-0.41
```

**Test Result**

Conduct version runs as expected.

```
Felixs-MacBook-Pro-2:conductr-cli felixsatyaputra$ conduct version
0.41
Supported API version(s): 1, 2
```

**Comment by fsat** [comment]
Manual test for https://github.com/typesafehub/conductr-cli/issues/180 is done successfully.

**Setup**

Run a local instal using pip3 install -e .

```
Felixs-MacBook-Pro-2:conductr-cli felixsatyaputra$ pip3 install -e .
Obtaining file:///Users/felixsatyaputra/workspace/typesafe-fsat/conductr-cli
Requirement already satisfied (use --upgrade to upgrade): requests>=2.11.1 in /usr/local/lib/python3.5/site-packages (from conductr-cli==0.41)
Requirement already satisfied (use --upgrade to upgrade): argcomplete>=0.8.1 in /usr/local/lib/python3.5/site-packages (from conductr-cli==0.41)
Requirement already satisfied (use --upgrade to upgrade): pyhocon==0.2.1 in /usr/local/lib/python3.5/site-packages (from conductr-cli==0.41)
Requirement already satisfied (use --upgrade to upgrade): arrow>=0.6.0 in /usr/local/lib/python3.5/site-packages (from conductr-cli==0.41)
Requirement already satisfied (use --upgrade to upgrade): jsonschema==2.4 in /usr/local/lib/python3.5/site-packages (from conductr-cli==0.41)
Requirement already satisfied (use --upgrade to upgrade): pager<4.0,>=3.3 in /usr/local/lib/python3.5/site-packages (from conductr-cli==0.41)
Requirement already satisfied (use --upgrade to upgrade): prettytable<1.0,>=0.7 in /usr/local/lib/python3.5/site-packages (from conductr-cli==0.41)
Requirement already satisfied (use --upgrade to upgrade): pygments<3.0,>=2.0 in /usr/local/lib/python3.5/site-packages (from conductr-cli==0.41)
Requirement already satisfied (use --upgrade to upgrade): six<2.0,>=1.9 in /usr/local/lib/python3.5/site-packages (from conductr-cli==0.41)
Requirement already satisfied (use --upgrade to upgrade): toml<1.0,>=0.9 in /usr/local/lib/python3.5/site-packages (from conductr-cli==0.41)
Requirement already satisfied (use --upgrade to upgrade): pyparsing==2.0.3 in /usr/local/lib/python3.5/site-packages (from pyhocon==0.2.1->conductr-cli==0.41)
Requirement already satisfied (use --upgrade to upgrade): python-dateutil in /usr/local/lib/python3.5/site-packages (from arrow>=0.6.0->conductr-cli==0.41)
Installing collected packages: conductr-cli
  Running setup.py develop for conductr-cli
Successfully installed conductr-cli-0.41
```

Remove the `~/.conductr` directory.

Patch conduct version to fail.

```
Felixs-MacBook-Pro-2:conductr-cli felixsatyaputra$ git diff
diff --git a/conductr_cli/conduct_version.py b/conductr_cli/conduct_version.py
index 79adf20..0a659e7 100644
--- a/conductr_cli/conduct_version.py
+++ b/conductr_cli/conduct_version.py
@@ -11,4 +11,5 @@ def version(args):
     log = logging.getLogger(__name__)
     log.screen(__version__)
     log.screen('Supported API version(s): {}'.format(', '.join(supported_api_versions())))
+    raise "boom"
     return True
```

**Test Result**

Conduct version fails with error, and the error is displayed as expected.

```
Felixs-MacBook-Pro-2:conductr-cli felixsatyaputra$ conduct version
0.41
Supported API version(s): 1, 2
Error: Encountered unexpected error.
Error: Reason: TypeError exceptions must derive from BaseException
Error: Further information of the error can be found in the error log file: /Users/felixsatyaputra/.conductr/errors.log
```

The logs are created successfully.

```
Felixs-MacBook-Pro-2:conductr-cli felixsatyaputra$ cat /Users/felixsatyaputra/.conductr/errors.log
2016-11-03 16:50:36,506: Failure running the following command: ['/usr/local/bin/conduct', 'version']
Traceback (most recent call last):
  File "/Users/felixsatyaputra/workspace/typesafe-fsat/conductr-cli/conductr_cli/main_handler.py", line 9, in run
    result = callback()
  File "/Users/felixsatyaputra/workspace/typesafe-fsat/conductr-cli/conductr_cli/conduct.py", line 6, in main_method
    conduct_main.run()
  File "/Users/felixsatyaputra/workspace/typesafe-fsat/conductr-cli/conductr_cli/conduct_main.py", line 372, in run
    is_completed_without_error = args.func(args)
  File "/Users/felixsatyaputra/workspace/typesafe-fsat/conductr-cli/conductr_cli/conduct_version.py", line 14, in version
    raise "boom"
TypeError: exceptions must derive from BaseException
```

**Cleanup**

Revert the patch which caused conduct version command to fail.

**Comment by fsat** [comment]
Manual test for shaking out standalone CLI is done successfully.

**Setup**

Run a local instal using pip3 install -e .

```
Felixs-MacBook-Pro-2:conductr-cli felixsatyaputra$ pip3 install -e .
Obtaining file:///Users/felixsatyaputra/workspace/typesafe-fsat/conductr-cli
Requirement already satisfied (use --upgrade to upgrade): requests>=2.11.1 in /usr/local/lib/python3.5/site-packages (from conductr-cli==0.41)
Requirement already satisfied (use --upgrade to upgrade): argcomplete>=0.8.1 in /usr/local/lib/python3.5/site-packages (from conductr-cli==0.41)
Requirement already satisfied (use --upgrade to upgrade): pyhocon==0.2.1 in /usr/local/lib/python3.5/site-packages (from conductr-cli==0.41)
Requirement already satisfied (use --upgrade to upgrade): arrow>=0.6.0 in /usr/local/lib/python3.5/site-packages (from conductr-cli==0.41)
Requirement already satisfied (use --upgrade to upgrade): jsonschema==2.4 in /usr/local/lib/python3.5/site-packages (from conductr-cli==0.41)
Requirement already satisfied (use --upgrade to upgrade): pager<4.0,>=3.3 in /usr/local/lib/python3.5/site-packages (from conductr-cli==0.41)
Requirement already satisfied (use --upgrade to upgrade): prettytable<1.0,>=0.7 in /usr/local/lib/python3.5/site-packages (from conductr-cli==0.41)
Requirement already satisfied (use --upgrade to upgrade): pygments<3.0,>=2.0 in /usr/local/lib/python3.5/site-packages (from conductr-cli==0.41)
Requirement already satisfied (use --upgrade to upgrade): six<2.0,>=1.9 in /usr/local/lib/python3.5/site-packages (from conductr-cli==0.41)
Requirement already satisfied (use --upgrade to upgrade): toml<1.0,>=0.9 in /usr/local/lib/python3.5/site-packages (from conductr-cli==0.41)
Requirement already satisfied (use --upgrade to upgrade): pyparsing==2.0.3 in /usr/local/lib/python3.5/site-packages (from pyhocon==0.2.1->conductr-cli==0.41)
Requirement already satisfied (use --upgrade to upgrade): python-dateutil in /usr/local/lib/python3.5/site-packages (from arrow>=0.6.0->conductr-cli==0.41)
Installing collected packages: conductr-cli
  Running setup.py develop for conductr-cli
Successfully installed conductr-cli-0.41
```

**Test Result**

Run a local sandbox using `sandbox run 0.1.0`. Sandbox starts up as expected.

```
Felixs-MacBook-Pro-2:conductr-cli felixsatyaputra$ sandbox run 0.1.0
Starting ConductR nodes..
Starting container cond-0..
8fbe0ac67a1cbf512f58e5868c8a9207fb701f056fdbae5fec354daf8deddc03
Waiting for ConductR to start..
ConductR has been started. Check current bundle status with: conduct info
```

Conduct version runs as expected.

```
Felixs-MacBook-Pro-2:conductr-cli felixsatyaputra$ conduct version
0.41
Supported API version(s): 1, 2
```

Bundles and config can be loaded, run, stopped, and unloaded using sandbox.

```
Felixs-MacBook-Pro-2:conductr-cli felixsatyaputra$ conduct load reactive-maps-backend-summary ~/tmp/test-config-a53237c1f4a067e13ef00090627fb3de8f31c1957ba2758a4fcd181a510c2e72.zip
Retrieving bundle...
Bintray credentials loaded from /Users/felixsatyaputra/.bintray/.credentials
Loading bundle from cache typesafe/bundle/reactive-maps-backend-summary
Retrieving from cache /Users/felixsatyaputra/.conductr/cache/reactive-maps-backend-summary-v1-abf60451c6af18adcc851d67b369b7f54810d12f3a0ef80a89bdc2d9dff49a10.zip
Retrieving configuration...
Bintray credentials loaded from /Users/felixsatyaputra/.bintray/.credentials
Retrieving file:///Users/felixsatyaputra/tmp/test-config-a53237c1f4a067e13ef00090627fb3de8f31c1957ba2758a4fcd181a510c2e72.zip
Loading bundle to ConductR...
Bundle abf60451c6af18adcc851d67b369b7f5-a53237c1f4a067e13ef00090627fb3de waiting to be installed
Bundle abf60451c6af18adcc851d67b369b7f5-a53237c1f4a067e13ef00090627fb3de installed
Bundle loaded.
Start bundle with: conduct run abf6045-a53237c
Unload bundle with: conduct unload abf6045-a53237c
Print ConductR info with: conduct info

Felixs-MacBook-Pro-2:conductr-cli felixsatyaputra$ conduct info
ID               NAME                           #REP  #STR  #RUN
f10a117-6249ee6  conductr-haproxy                  1     0     1
f217626          eslite                            1     0     1
abf6045-a53237c  reactive-maps-backend-summary     1     0     0

Felixs-MacBook-Pro-2:conductr-cli felixsatyaputra$ conduct run react
Bundle run request sent.
Bundle abf60451c6af18adcc851d67b369b7f5-a53237c1f4a067e13ef00090627fb3de waiting to reach expected scale 1
Bundle abf60451c6af18adcc851d67b369b7f5-a53237c1f4a067e13ef00090627fb3de has scale 0, expected 1
Bundle abf60451c6af18adcc851d67b369b7f5-a53237c1f4a067e13ef00090627fb3de expected scale 1 is met
Stop bundle with: conduct stop abf6045-a53237c
Print ConductR info with: conduct info

Felixs-MacBook-Pro-2:conductr-cli felixsatyaputra$ conduct info
ID               NAME                           #REP  #STR  #RUN
f10a117-6249ee6  conductr-haproxy                  1     0     1
f217626          eslite                            1     0     1
abf6045-a53237c  reactive-maps-backend-summary     1     0     1

Felixs-MacBook-Pro-2:conductr-cli felixsatyaputra$ conduct events react
TIME      EVENT                                         DESC
17:02:22  conductr.loadExecutor.bundleWritten           Bundle written
17:02:28  conductr.scaleScheduler.scaleBundleRequested  Scale bundle requested: scale=1
17:02:29  conductr.launcher.bundleStarted               Bundle started: host=172.17.0.2

Felixs-MacBook-Pro-2:conductr-cli felixsatyaputra$ conduct logs react
TIME      HOST          LOG
17:02:30  8fbe0ac67a1c  [INFO] [11/03/2016 06:02:30.367] [main] [Remoting] Remoting now listens on addresses: [akka.tcp://reactive-maps-1@172.17.0.2:10917]
17:02:30  8fbe0ac67a1c  [INFO] [11/03/2016 06:02:30.378] [main] [Cluster(akka://reactive-maps-1)] Cluster Node [akka.tcp://reactive-maps-1@172.17.0.2:10917] - Starting up...
[WARN] [11/03/2016 06:02:30.378] [main] [Cluster(akka://reactive-maps-1)] [akka.cluster.auto-down] setting is replaced by [akka.cluster.auto-down-unreachable-after]
17:02:30  8fbe0ac67a1c  [INFO] [11/03/2016 06:02:30.483] [main] [Cluster(akka://reactive-maps-1)] Cluster Node [akka.tcp://reactive-maps-1@172.17.0.2:10917] - Registered cluster JMX MBean [akka:type=Cluster]
17:02:30  8fbe0ac67a1c  [INFO] [11/03/2016 06:02:30.484] [main] [Cluster(akka://reactive-maps-1)] Cluster Node [akka.tcp://reactive-maps-1@172.17.0.2:10917] - Started up successfully
17:02:30  8fbe0ac67a1c  [INFO] [11/03/2016 06:02:30.490] [reactive-maps-1-akka.actor.default-dispatcher-4] [Cluster(akka://reactive-maps-1)] Cluster Node [akka.tcp://reactive-maps-1@172.17.0.2:10917] - Metrics will be retreived from MBeans, and may be incorrect on some platforms. To increase metric accuracy add the 'sigar.jar' to the classpath and the appropriate platform-specific native libary to 'java.library.path'. Reason: java.lang.ClassNotFoundException: org.hyperic.sigar.Sigar
17:02:30  8fbe0ac67a1c  [INFO] [11/03/2016 06:02:30.498] [reactive-maps-1-akka.actor.default-dispatcher-4] [Cluster(akka://reactive-maps-1)] Cluster Node [akka.tcp://reactive-maps-1@172.17.0.2:10917] - Metrics collection has started successfully
17:02:30  8fbe0ac67a1c  [INFO] [11/03/2016 06:02:30.573] [reactive-maps-1-akka.actor.default-dispatcher-14] [Cluster(akka://reactive-maps-1)] Cluster Node [akka.tcp://reactive-maps-1@172.17.0.2:10917] - Node [akka.tcp://reactive-maps-1@172.17.0.2:10917] is JOINING, roles [backend-summary]
17:02:31  8fbe0ac67a1c  [INFO] [11/03/2016 06:02:31.533] [reactive-maps-1-akka.actor.default-dispatcher-19] [Cluster(akka://reactive-maps-1)] Cluster Node [akka.tcp://reactive-maps-1@172.17.0.2:10917] - Leader is moving node [akka.tcp://reactive-maps-1@172.17.0.2:10917] to [Up]
17:02:31  8fbe0ac67a1c  [WARN] [11/03/2016 06:02:31.590] [reactive-maps-1-akka.actor.default-dispatcher-17] [akka.diagnostics.ConfigChecker] Typesafe recommendation: Use Akka Split Brain Resolver instead of auto-down, since auto-down may cause the cluster to be split into two separate disconnected clusters when there are network partitions, long garbage collection pauses or system overload. This is especially important if you use Cluster Singleton, Cluster Sharding, or Persistence. Related config properties: [akka.cluster.auto-down = on]. Corresponding default values: [akka.cluster.auto-down = off]. You may disable this check by adding [auto-down] to configuration string list akka.diagnostics.checker.disabled-checks. Please use http://support.typesafe.com/ if you need more advice around this warning.
17:02:31  8fbe0ac67a1c  [WARN] [11/03/2016 06:02:31.598] [reactive-maps-1-akka.actor.default-dispatcher-17] [akka.diagnostics.ConfigChecker] Typesafe recommendation: akka.cluster.seed-nodes.0 is not an Akka configuration setting. Is it a typo or is it placed in the wrong section? Application specific properties should be placed outside the "akka" config tree. Related config properties: [akka.cluster.seed-nodes.0]. You may disable this check by adding [typo] to configuration string list akka.diagnostics.checker.disabled-checks. Please use http://support.typesafe.com/ if you need more advice around this warning.

Felixs-MacBook-Pro-2:conductr-cli felixsatyaputra$ conduct stop react
Bundle stop request sent.
Bundle abf60451c6af18adcc851d67b369b7f5-a53237c1f4a067e13ef00090627fb3de waiting to reach expected scale 0
Bundle abf60451c6af18adcc851d67b369b7f5-a53237c1f4a067e13ef00090627fb3de expected scale 0 is met
Unload bundle with: conduct unload abf6045-a53237c
Print ConductR info with: conduct info

Felixs-MacBook-Pro-2:conductr-cli felixsatyaputra$ conduct info
ID               NAME                           #REP  #STR  #RUN
f10a117-6249ee6  conductr-haproxy                  1     0     1
f217626          eslite                            1     0     1
abf6045-a53237c  reactive-maps-backend-summary     1     0     0

Felixs-MacBook-Pro-2:conductr-cli felixsatyaputra$ conduct unload react
Bundle unload request sent.
Bundle abf60451c6af18adcc851d67b369b7f5-a53237c1f4a067e13ef00090627fb3de waiting to be uninstalled
Bundle abf60451c6af18adcc851d67b369b7f5-a53237c1f4a067e13ef00090627fb3de uninstalled
Print ConductR info with: conduct info

Felixs-MacBook-Pro-2:conductr-cli felixsatyaputra$ conduct info
ID               NAME              #REP  #STR  #RUN
f10a117-6249ee6  conductr-haproxy     1     0     1
f217626          eslite               1     0     1
```

Sandbox can be stopped as expected.

```
Felixs-MacBook-Pro-2:conductr-cli felixsatyaputra$ sandbox stop
Stopping ConductR..
cond-0
```
