### ISSUE TITLE
conduct load times out when uploading with a slow internet connection

### ISSUE THREAD

**Issue by longmuir** [typesafehub/conductr-cli#220]
I've experienced this when trying to upload bundles on slow internet connections. It seems to happen pretty consistently (ie I won't be able to upload my bundle on this connection). After a few minutes, the connection always seems to break as follows. I'd estimate this bundle might take ~10 minutes to upload if successful on this connection.

It might be related to issue #48 or issue #183, though not sure.

From the CLI (V0.51):
`Jamies-MBP:bundle jamielongmuir$ conduct load --host tdclddlnva015.ebiz.verizon.com /Users/jamielongmuir/code/verizon/soco-akka/db_consumer/target/bundle/soco-db_consumer-v0-c8111ac2bb58c64d3005e4d61c82614b52b96ab1d6a187631d5a421a0884e9c5.zip /Users/jamielongmuir/code/verizon/soco-akka/db_consumer/target/bundle/config-a24e4a04673bd28ef3fddb67d6d4ac6845fc70ae075d6296d443ccfef5c6305e.zip
Retrieving bundle...
Bintray credentials loaded from /Users/jamielongmuir/.bintray/.credentials
Retrieving file:///Users/jamielongmuir/code/verizon/soco-akka/db_consumer/target/bundle/soco-db_consumer-v0-c8111ac2bb58c64d3005e4d61c82614b52b96ab1d6a187631d5a421a0884e9c5.zip
Retrieving configuration...
Bintray credentials loaded from /Users/jamielongmuir/.bintray/.credentials
Retrieving file:///Users/jamielongmuir/code/verizon/soco-akka/db_consumer/target/bundle/config-a24e4a04673bd28ef3fddb67d6d4ac6845fc70ae075d6296d443ccfef5c6305e.zip
Loading bundle to ConductR...
Error: Unable to contact ConductR.                ]   8%
Error: Reason: ('Connection aborted.', BrokenPipeError(32, 'Broken pipe'))
Error: Make sure it can be accessed at http://tdclddlnva015.ebiz.verizon.com:9005/v2/bundles
`
ConductR (v1.1.11) Logs:
`2016-11-21T19:59:36Z tdclddlnva015.ebiz.verizon.com ERROR ActorSystemImpl [sourceThread=conductr-akka.actor.default-dispatcher-6, akkaTimestamp=19:59:36.629UTC, akkaSource=akka.actor.ActorSystemImpl(conductr), sourceActorSystem=conductr] - Outgoing response stream error
akka.http.scaladsl.model.ParsingException: Unexpected end of multipart entity
	at akka.http.scaladsl.unmarshalling.MultipartUnmarshallers$$anonfun$multipartUnmarshaller$1$$anonfun$apply$1$$anonfun$apply$2$$anonfun$1.applyOrElse(MultipartUnmarshallers.scala:108)
	at akka.http.scaladsl.unmarshalling.MultipartUnmarshallers$$anonfun$multipartUnmarshaller$1$$anonfun$apply$1$$anonfun$apply$2$$anonfun$1.applyOrElse(MultipartUnmarshallers.scala:103)
	at akka.stream.impl.fusing.Collect$$anon$2$$anonfun$4.apply(Ops.scala:199)
	at akka.stream.impl.fusing.SupervisedGraphStageLogic.withSupervision(Ops.scala:166)
	at akka.stream.impl.fusing.Collect$$anon$2.onPush(Ops.scala:201)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:747)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:736)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:616)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:471)
	at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:423)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:603)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$shortCircuitBatch(ActorGraphInterpreter.scala:594)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:619)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:529)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run$$original(Mailbox.scala:224)
	at akka.dispatch.Mailbox.run(Mailbox.scala:29)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
`

**Comment by huntc** [comment]
This CLI is old and the timeout issue has been addressed. We now provide a progress bar when uploading.
