### ISSUE TITLE
Possible Sandbox error on shutdown

### ISSUE THREAD

**Issue by longshorej** [typesafehub/conductr-cli#310]
I'm guessing this is related to the psutil commit. When Tom runs sandbox stop, he gets a stack trace. It appears that psutil is returning `NoneType` instead of `[]` which is causing problems.

----------------------------------------------------------

(from Slack)

**tompeck** 
Hi #prod-suite team.  Minor one, but I'm getting this error when I run `sandbox stop`

**tompeck**
```
2017-02-08 13:13:21,175: Failure running the following command: ['sandbox', 'stop']
Traceback (most recent call last):
  File "conductr_cli/main_handler.py", line 14, in run
  File "conductr_cli/sandbox.py", line 6, in main_method
  File "conductr_cli/validation.py", line 407, in handler
  File "conductr_cli/sandbox_main.py", line 224, in run
  File "conductr_cli/sandbox_stop.py", line 8, in stop
  File "conductr_cli/sandbox_stop_jvm.py", line 23, in stop
  File "conductr_cli/sandbox_stop_jvm.py", line 63, in kill_processes
  File "conductr_cli/sandbox_stop_jvm.py", line 49, in wait_for_processes
  File "conductr_cli/sandbox_common.py", line 81, in find_pids
  File "conductr_cli/sandbox_common.py", line 56, in calculate_pids
TypeError: 'NoneType' object is not iterable
```

**jason.longshore**
I think this is related to a commit from a couple weeks ago. At a glance, I'd say the output is harmless and I'll create an issue to look into fixing it

**tompeck**
Cheers Jason

**Comment by longshorej** [comment]
Markus beat me to it - https://github.com/typesafehub/conductr-cli/pull/309
