### ISSUE TITLE
DC/OS Unable to load-license dcos.errors.DCOSException: Invalid HTTP response: server returned an HTTP 401 response with no 'www-authenticate' field

### ISSUE THREAD

**Issue by edwardcallahan** [typesafehub/conductr-cli#421]
```
 dcos conduct load-license
Error: Encountered unexpected error.
Error: Reason: DCOSException Invalid HTTP response: server returned an HTTP 401 response with no 'www-authenticate' field

2017-04-18 23:43:29,054: Failure running the following command: ['/home/ubuntu/.dcos/subcommands/conductr/env/bin/dcos-conduct', 'conduct', 'load-license']
Traceback (most recent call last):
  File "conductr_cli/main_handler.py", line 14, in run
  File "conductr_cli/conduct.py", line 6, in main_method
  File "conductr_cli/conduct_main.py", line 557, in run
  File "conductr_cli/validation.py", line 40, in handler
  File "conductr_cli/validation.py", line 56, in handler
  File "conductr_cli/validation.py", line 506, in handler
  File "conductr_cli/validation.py", line 543, in handler
  File "conductr_cli/conduct_load_license.py", line 28, in load_license
  File "conductr_cli/license.py", line 42, in download_license
  File "conductr_cli/conduct_request.py", line 16, in get
  File "dcos/http.py", line 269, in get
  File "dcos/http.py", line 232, in request
  File "dcos/http.py", line 156, in _request_with_auth
  File "dcos/http.py", line 425, in _get_http_auth
dcos.errors.DCOSException: Invalid HTTP response: server returned an HTTP 401 response with no 'www-authenticate' field
ubuntu@ip-10-100-1-226:~/.lightbend$ dcos conduct info
UNLICENSED - please use "conduct load-license" to use more agents. Additional agents are freely available for registered users.
Licensed To: unknown
Max ConductR agents: 1
ConductR Version(s): 2.1.*
Grants: conductr, cinnamon, akka-sbr

ID         NAME              TAG  #REP  #STR  #RUN  ROLES
6cc7dbc    visualizer                1     0     0  web
bdfa43d    conductr-haproxy          1     0     0  haproxy
! b1157bd  test-bundle               1     0     0  web
There are errors: use `conduct events` or `conduct logs` for further information


```

**Comment by huntc** [comment]
This should now be resolved via #418
