### ISSUE TITLE
dcos conduct load-license fails

### ISSUE THREAD

**Issue by huntc** [typesafehub/conductr-cli#425]
`dcos conduct load-license` with the CLI v.1.2.3 yields a problem:

```
 dcos conduct load-license
Error: Encountered unexpected error.
Error: Reason: AttributeError 'Namespace' object has no attribute 'host'
Error: Further information of the error can be found in the error log file: /home/ubuntu/.conductr/errors.log
```

Looking at the stacktrace yields:

```
ubuntu@ip-10-100-1-226:~/.lightbend$ tail /home/ubuntu/.conductr/errors.log
Traceback (most recent call last):
  File "conductr_cli/main_handler.py", line 14, in run
  File "conductr_cli/conduct.py", line 6, in main_method
  File "conductr_cli/conduct_main.py", line 557, in run
  File "conductr_cli/validation.py", line 39, in handler
  File "conductr_cli/validation.py", line 55, in handler
  File "conductr_cli/validation.py", line 505, in handler
  File "conductr_cli/validation.py", line 523, in handler
  File "conductr_cli/conduct_load_license.py", line 31, in load_license
AttributeError: 'Namespace' object has no attribute 'host'
```

**Comment by huntc** [comment]
Resolved via #426
