### ISSUE TITLE
Improve error message if HTTP request too large

### ISSUE THREAD

**Issue by hseeberger** [typesafehub/conductr-cli#48]
See https://github.com/typesafehub/conductr/issues/590.

**Comment by huntc** [comment]
@fsat Didn't we do this?

**Comment by fsat** [comment]
From my memory, not within the CLI. To be sure, I'd like to do the actual test.

**Comment by huntc** [comment]
@fsat Any further thoughts?

**Comment by fsat** [comment]
This is still not handled well in the CLI - if entity size exception is encountered by ConductR, the CLI prints out the following:

```
Loading bundle to ConductR...
Error: Unable to contact ConductR.
Error: Reason: ('Connection aborted.', BrokenPipeError(32, 'Broken pipe'))
Error: Start the ConductR sandbox with: sandbox run IMAGE_VERSION
```

The ConductR control protocol will record the following exception as expected:

```
2016-02-24T05:36:40Z 192-168-1-5.tpgi.com.au ERROR ActorSystemImpl akka.actor.ActorSystemImpl(conductr) - Error during processing of request HttpRequest(HttpMethod(POST),http://127.0.0.1:9005/bundles,List(Remote-Address: 127.0.0.1:64906, Host: 127.0.0.1:9005, Connection: keep-alive, Accept-Encoding: gzip, deflate, Accept: */*, User-Agent: python-requests/2.9.1),HttpEntity.Default(multipart/form-data; boundary=34fd564fb3144797b65d463bd8d52664; charset=UTF-8,44233050,akka.stream.scaladsl.Source@1bb49906),HttpProtocol(HTTP/1.1))
akka.http.scaladsl.model.EntityStreamSizeException: null
    at akka.http.scaladsl.model.HttpEntity$$anonfun$limitable$1$$anon$1.preStart(HttpEntity.scala:498) ~[com.typesafe.akka.akka-http-core-experimental_2.11-2.0.3.jar:na]
    at akka.stream.stage.AbstractStage$PushPullGraphLogic.preStart(Stage.scala:158) ~[com.typesafe.akka.akka-stream-experimental_2.11-2.0.3.jar:na]
```

**Comment by huntc** [comment]
@fsat Does this remain an issue?

**Comment by huntc** [comment]
Unfixable - Python requests library issue.
