### ISSUE TITLE
Lots of blank lines for conduct log

### ISSUE THREAD

**Issue by huntc** [typesafehub/conductr-cli#59]
Messages appear with lots of blank lines in between - what's happening?

![screen shot 2015-09-11 at 5 08 23 pm](https://cloud.githubusercontent.com/assets/694893/9808998/c318a5f6-58a7-11e5-83c8-e4c6ae1bc1f6.png)

Here's the corresponding json:

``` json
[
    {
        "host": "dc9f9cab9411",
        "message": "Set conductr index pattern as default\n",
        "timestamp": "2015-09-11T07:00:35.814Z"
    },
    {
        "host": "dc9f9cab9411",
        "message": "{\"_index\":\".kibana\",\"_type\":\"config\",\"_id\":\"4.1.2\",\"_version\":1,\"created\":true}",
        "timestamp": "2015-09-11T07:00:35.85Z"
    },
    {
        "host": "dc9f9cab9411",
        "message": "Refresh conductr index pattern\n",
        "timestamp": "2015-09-11T07:00:35.851Z"
    },
    {
        "host": "dc9f9cab9411",
        "message": "{\"_shards\":{\"total\":1,\"successful\":1,\"failed\":0}}",
        "timestamp": "2015-09-11T07:00:35.882Z"
    },
    {
        "host": "dc9f9cab9411",
        "message": "module.js:340\n    throw err;\n          ^\n",
        "timestamp": "2015-09-11T07:00:35.94Z"
    },
    {
        "host": "dc9f9cab9411",
        "message": "\n",
        "timestamp": "2015-09-11T07:00:35.94Z"
    },
    {
        "host": "dc9f9cab9411",
        "message": "Error: Cannot find module 'lodash'\n    at Function.Module._resolveFilename (module.js:338:15)\n    at Function.Module._load (module.js:280:25)\n    at Module.require (module.js:364:17)\n    at require (module.js:380:17)\n    at Object.<anonymous> (/tmp/53dad3668b1cb31432ae853bb61de656/53dad3668b1cb31432ae853bb61de6565adba4e270167ca5c13066abcfdf2f04/conductr-kibana-0.1.0/src/config/index.js:1:71)\n    at Module._compile (module.js:456:26)\n    at Object.Module._extensions..js (module.js:474:10)\n    at Module.load (module.js:356:32)\n    at Function.Module._load (module.js:312:12)\n    at Module.require (module.js:364:17)\n",
        "timestamp": "2015-09-11T07:00:35.943Z"
    },
    {
        "host": "dc9f9cab9411",
        "message": "Component conductr-kibana-0.1.0 exited with 8\nStopping bundle\n",
        "timestamp": "2015-09-11T07:00:35.944Z"
    },
    {
        "host": "dc9f9cab9411",
        "message": "/tmp/53dad3668b1cb31432ae853bb61de656/start: line 19: kill: (352) - No such process\n/tmp/53dad3668b1cb31432ae853bb61de656/start: line 19: kill: (349) - No such process\n",
        "timestamp": "2015-09-11T07:00:35.964Z"
    },
    {
        "host": "dc9f9cab9411",
        "message": "/tmp/53dad3668b1cb31432ae853bb61de656/start: line 20: kill: (352) - No such process\n/tmp/53dad3668b1cb31432ae853bb61de656/start: line 20: kill: (349) - No such process\n",
        "timestamp": "2015-09-11T07:00:45.789Z"
    }
]
```

Perhaps we should always strip off the last newline from within the CLI.

**Comment by huntc** [comment]
@fsat Have you seen this before?

**Comment by markusjura** [comment]
Fixed with PR #65.

**Comment by typesafe-tools** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;2aYWyvJb&#x2F;121-tactical-activities"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Tactical Activities</a>

**Comment by typesafe-tools** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;2aYWyvJb&#x2F;121-tactical-activities"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Tactical Activities</a>
